query HomeContent {
	site: _site {
		favicon: faviconMetaTags {
			attributes
			content
			tag
		}
	}

	blog {
		seo: _seoMetaTags {
			attributes
			content
			tag
		}
	}

	allPosts: allPosts(orderBy: date_DESC, filter: { category: {eq: "A1jn-YRUQdGUsH0MFKz0tA"} }) {
		title
		slug
		excerpt
		date
	}
}
