query ServiceContent($slug: String) {
	site: _site {
		favicon: faviconMetaTags {
			attributes
			content
			tag
		}
	}

	post(filter: { slug: { eq: $slug } }) {
		seo: _seoMetaTags {
			attributes
			content
			tag
		}
		title
		slug
		content {
			...StructuredTextFragment
		}
		date
		ogImage: coverImage {
			url(imgixParams: { fm: jpg, fit: crop, w: 2000, h: 1000 })
		}
		coverImage {
			...ImageFragment
		}
}
}